### ISSUE TITLE
Add migration notes for Rusoto 0.39.0 error handling

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#110]
https://github.com/rusoto/rusoto/issues/1354 needs work here, too. 😄

**Comment by itsHabib** [comment]
Taking a look at this

**Comment by itsHabib** [comment]
@matthewkmayer  I think this should be a migration for 0.38.0. When testing the versions, that is where the error occurred and according to the release notes that is when the new `RusotoError` enum was released.
