### ISSUE TITLE
Broken link on https://rusoto.org/lambdas.html

### ISSUE THREAD

**Issue by guidorice** [rusoto/rusoto.github.io#115]
In Resources and Links
-    AWS Lambda and DynamoDB with Rust

Links to https://medium.com/@kkostov/aws-lambda-dynamodb-rust-df84bd15d29b
> Error 410
> The author deleted this Medium story.

Should I submit a PR to remove that section? Unless anyone has a better article to replace it with?

**Comment by matthewkmayer** [comment]
Thanks for the report.

I'm not aware of any other article highlighting the use of Rusoto in a lambda. I'd love to have a fresh example written, maybe hosted on rusoto.org so it won't go away.

For now, a PR removing the link would be appreciated. 👍

**Comment by guidorice** [comment]
@matthewkmayer ok sounds good. In the future I hope to contribute more to the docs.

Thanks for Rusoto btw!
