### ISSUE TITLE
Add walkthroughs for Rusoto in Lambdas

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#117]
Two super useful posts on Medium have been removed. We should have our own walkthroughs using Rusoto in a Lambda so we're less reliant on information that could go away. 👍

**Comment by realharry** [comment]
I'm looking for a simple example as well: https://github.com/rusoto/rusoto/issues/1721

Thanks!

**Comment by iliana** [comment]
@davidbarsky do you think you'd be up to this task, since it could potentially do double-duty as both Rusoto documentation and docs for the new Lambda runtime? :)

Doesn't have to be released yet, we can update the documentation when a release happens.

**Comment by davidbarsky** [comment]
@iliana Yeah, I've been working on docs and tests this past weekend, but I haven't gotten a chance to publish a PR yet. I'll ping you on this issue when I do.

**Comment by matthewkmayer** [comment]
There's a new [blog post](http://jamesmcm.github.io/blog/2020/04/19/data-engineering-with-rust-and-aws-lambda/#en) with [source code](https://github.com/jamesmcm/rust-lambda-test) we could link to as an easy win. 👍

**Comment by matthewkmayer** [comment]
We need this but it's been so long it probably won't happen.
