### ISSUE TITLE
Broken link on lambdas page

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#118]
Similar to https://github.com/rusoto/rusoto.github.io/issues/115, https://medium.com/@kkostov/rust-aws-lambda-30a1b92d4009 has been deleted as well. 😢 

We should remove the link or see if there's an archive.org version available until we make our own walkthrough for https://rusoto.org . See https://github.com/rusoto/rusoto.github.io/issues/117 .

**Comment by jerusdp** [comment]
The original example is available on the author's website: 
https://www.iamkonstantin.eu/blog/post-2018-12-02/

**Comment by iliana** [comment]
closed in #134
