### ISSUE TITLE
Update supported services for Rusoto 0.41.0

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#119]
Like https://github.com/rusoto/rusoto.github.io/issues/108 we need to update services supported in the new version of Rusoto. 

The [Rusoto 0.41.0 release notes](https://github.com/rusoto/rusoto/releases/tag/rusoto-v0.41.0) have the two new services mentioned. 👍

**Comment by plwai** [comment]
Hi, I will pick up for this.
