### ISSUE TITLE
Create a complete Rusoto tutorial

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#123]
We should have a new page on https://rusoto.org and a companion complete example of a project using Rusoto, including:

* how to create AWS access keys/credentials
* supplying AWS credentials in ways that follow [best practices](https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html)

Reference: https://github.com/rusoto/rusoto/issues/1565

**Comment by matthewkmayer** [comment]
I think https://github.com/matthewkmayer/ec2-itinerary should be able to work for this. 👍 It's in progress but should fill our needs for this issue.

**Comment by jpalomaki** [comment]
@matthewkmayer What kind of tutorial project (deployment) would be of most interest here: CLI app, container (ECS), lambda, EC2?

**Comment by matthewkmayer** [comment]
I think the best options are either a lambda or an ECS container. Those would have the least moving parts around AWS infrastructure and incidentals, allowing the focus to be on use of Rusoto. 👍

**Comment by matthewkmayer** [comment]
We need this but it's been so long it probably won't happen.
