### ISSUE TITLE
Configure SSL support

### ISSUE THREAD

**Issue by indiv0** [rusoto/rusoto.github.io#13]
I think https://github.com/rusoto/rusoto.github.io/issues/8 will provide us a way to do this via GitBook, so this is blocked by https://github.com/rusoto/rusoto.github.io/issues/8.

If that falls through, we can set it up with CloudFlare.

**Comment by indiv0** [comment]
Additionally, due to the changes in #18, the `domain` variable in `book.json` will need to be updated to point to HTTPS.

**Comment by matthewkmayer** [comment]
This should be handled by #8 since we're going all-in on AWS: S3 bucket website with Cloudfront serving it over https.
