### ISSUE TITLE
Replace IRC links for Rusoto discussion with Discord links

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#131]
https://rusoto.org/help.html references IRC and it's not used much. At least I don't hang out there. 😉 

There is an [active Discord channel](https://github.com/rusoto/rusoto/issues/1651#issuecomment-578448231) we could replace the link with.

@iliana does this sound good to you?

**Comment by iliana** [comment]
Yes, we should absolutely do that.
