### ISSUE TITLE
Setup links open in new tab/window

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#15]
From http://rusoto.org/setup.html if you click any of the three links for setting up Rusoto on stable, nightly or hybrid, the link opens in a new tab.  Since it's redirecting to a page inside of rusoto.org it's my preference to open in the same tab/window.

**Comment by indiv0** [comment]
Yeah I wrote the domain-based links before we had an actual domain, so those need to be replaced. I'll get on that. I think I'll set it up with templates (IIRC GitBook can do that) so we can easily change it later.
