### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by indiv0** [rusoto/rusoto.github.io#2]
@adimarco @jimmycuadra @matthewkmayer if you'd like, we can add Google Analytics to the GitBook, for analytics and whatnots. If you'd like me go ahead with it, just enable Google Analytics for the domain and provide me with the Google Analytics tracking ID (e.g. "UA-XXXX-Y").

**Comment by jimmycuadra** [comment]
-1 from me, but just because my personal view about tracking people is that it's invasive and unnecessary. I don't care what Rusoto does if everyone else thinks it would be valuable.

**Comment by indiv0** [comment]
Personally I'm split on it because I'm against tracking people as well on principle, but on my (earlier) personal projects I have found analytics to be helpful at times. So I guess I'm in the same position.

**Comment by matthewkmayer** [comment]
I've no strong opinion on it.

**Comment by indiv0** [comment]
I'll close this, pending a distinct need for analytics.
