### ISSUE TITLE
Run Cloudfront invalidation after publish

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#39]
After publishing it can take Cloudfront up to 24 hours to get the new docs we publish.  Suboptimal for sure.

**Comment by indiv0** [comment]
Wouldn't this just be a matter of adjusting the Cloudfront cache TTLs?

**Comment by matthewkmayer** [comment]
That's another option, it would be slightly more expensive since there would be more requests from Cloudfront to the S3 bucket.  As long as we do less than a thousand deploys a month, invalidation would be faster and cheaper.

**Comment by matthewkmayer** [comment]
🎉
