### ISSUE TITLE
Update documentation links to not be SSL

### ISSUE THREAD

**Issue by indiv0** [rusoto/rusoto.github.io#40]
Currently, if you attempt to access the documentation via the "API Documentation" button or other methods from the SSL version of the rusoto website (e.g. https://rusoto.org) it takes you to the SSL page for the documentation, which doesn't work. These links need to be updated to not be relative to the pages their on to avoid this.

**Comment by matthewkmayer** [comment]
Is this something different than https://github.com/rusoto/rusoto.github.io/pull/41 which fixes https://github.com/rusoto/rusoto.github.io/issues/27 ?  If so can I get an example of what doesn't work?

**Comment by indiv0** [comment]
Sorry, I missed #27. No, this issue is a duplicate, which I will close. As for #41, you got the fix backwards :P
