### ISSUE TITLE
Add a resources page with links?

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#56]
Should we have a page with links to projects using Rusoto and other information [such as my Rusoto walkthrough](https://matthewkmayer.github.io/blag/public/post/rusoto-rds-mk2/)?

**Comment by indiv0** [comment]
I think this is a great idea as (slightly) outdated documentation or examples seem to burn rusoto users pretty frequently. Pointing them at active projects like [kaws](https://github.com/InQuicker/kaws) would help with that, I think.

**Comment by matthewkmayer** [comment]
I think with https://github.com/rusoto/rusoto.github.io/issues/96 and our use of `skeptic` in this repo and the main Rusoto repo, we're in a good state for not having outdated docs.

However, it'd still be nice to have a list of projects using Rusoto so people can see its use outside of first-party repositories.

**Comment by matthewkmayer** [comment]
We've got https://rusoto.org/extensions-on-rusoto.html which fulfills this ticket. 👍
