### ISSUE TITLE
Update supported services list

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#69]
We're missing a few services Rusoto supports: https://github.com/rusoto/rusoto.github.io/blob/source/src/supported-aws-services.md should have more services.

A complete list of services Rusoto supports can be found [in its Cargo.toml file](https://github.com/rusoto/rusoto/blob/master/Cargo.toml).

Example PR that adds more services: https://github.com/rusoto/rusoto.github.io/pull/65 .

Keeping the list of supported services alphabetized would be greatly appreciated. 😄

**Comment by tuxinaut** [comment]
Small question, how is the definition for is if a service is **Stable** or **Needs improvement**

**Comment by matthewkmayer** [comment]
Great question!  We don't really have a set of guidelines for it and in https://github.com/rusoto/rusoto.github.io/issues/64 I suggest we get rid of the stability tags.

To complete this PR, new services can be marked as `Needs improvement`.  😄

**Comment by tuxinaut** [comment]
@matthewkmayer thank you very much for clarifying that. I'm going to start today evening.
