### ISSUE TITLE
Migrate back to GitBooks instead of GitHub Pages

### ISSUE THREAD

**Issue by indiv0** [rusoto/rusoto.github.io#8]
See prior discussion here: https://github.com/rusoto/rusoto/issues/366

~~Blocked while I await a response regarding a free paid account from GitBooks.~~

**Comment by indiv0** [comment]
OK so GitBooks got back to me, and it turns out they added a feature to their site since I emailed them, so now I can create an organization repo for free (which I did!). So the GitBook is available at https://rusoto.gitbooks.io/rusoto/content/. I've configured it to work with `rusoto.org`, so the only thing left is for @matthewkmayer to create a `CNAME` record for `rusoto.org` that points to `www.gitbooks.io`. This will make `https://rusoto.org` resolve to the GitBook (notice the SSL!).

However, once that's done we'll be serving the GitBook via GitBook's website, and not GitHub Pages. Should I disable our integration with GitHub Pages? This will mean that GitBook would be entirely in charge of building and serving the website (meaning that the repo will only store the source, not the built website).

I'm not sure if that's the best option. Personally I'm in favour of just adding the GitBook support and leaving the GitHub Pages integration in case we need it in the future (and so we always have a static copy of the built website available).

**Comment by matthewkmayer** [comment]
I just set the CNAME to `www.gitbooks.io` as requested. Waiting for DNS to get the update to ensure it works.

Agreed keeping both gitbook and github pages is the way to go.

**Comment by matthewkmayer** [comment]
I changed the `www` CNAME and https://www.rusoto.org/ 404s on gitbooks' end.  Something we have to change there?

I've signed in to gitbooks with my github account, perhaps I can be added to the rusoto org there.  Not sure how it works on gitbooks.

**Comment by indiv0** [comment]
Weird that it's giving a 404, but I think it has something to do with the fact that you made `www` the CNAME and not the root domain. Try the root domain and see what happens. I'll add you to the rusoto org on GitBooks so you can test things further.

**Comment by matthewkmayer** [comment]
Also, as far as I can tell, Route 53 doesn't let the apex domain record be a cname or alias for anything outside of AWS.  You can point to an S3 bucket web site, but not gitbooks.io.

**Comment by indiv0** [comment]
In that case, we either need to change our DNS provider so that we can setup a root CNAME (although IIRC most providers frown on that), or make our domain www.rusoto.org in the GitBook configuration. There might be some options I'm missing though. Personally, I'd very much prefer that https://rusoto.org be our domain (i.e. root domain + SSL).

**Comment by adimarco** [comment]
CloudFlare does CNAME flattening for apex domain records in the way that we want - https://support.cloudflare.com/hc/en-us/articles/200169056-CNAME-Flattening-RFC-compliant-support-for-CNAME-at-the-root

**Comment by matthewkmayer** [comment]
When I get the time I plan on making an S3 bucket the apex domain points to that redirects to gitbooks.  See http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html .

**Comment by matthewkmayer** [comment]
@indiv0 can you could double check the permissions on my account on gitbooks?  I don't see a settings tab anywhere.

**Comment by indiv0** [comment]
Yup, my bad. I forgot to elevate your permissions after making you a contributor. You are now an owner of the project.

Also, settings page: https://www.gitbook.com/book/rusoto/rusoto/settings

**Comment by matthewkmayer** [comment]
Something is still off, not seeing anything new on my end.  Logged out and logged back in, still nothing.  Perhaps I need to be added to the rusoto group on gitbooks.

**Comment by indiv0** [comment]
You are now an administrator for the rusoto group as well.

**Comment by matthewkmayer** [comment]
👍 I see the settings page now.

**Comment by matthewkmayer** [comment]
S3 redirect didn't work with https and I've had a few people point me to using Cloudfront for SSL and redirects.  At that point it may be easier to publish docs to an S3 bucket and use Cloudfront for that.

I'll look more into Cloudflare first.

**Comment by matthewkmayer** [comment]
@adimarco and I spent some time mucking with this today using his Cloudflare account.  We can seem to get either www.rusoto.org working OR rusoto.org working.  If I change the gitbook custom domain setting it can work with one but not the other.

**Comment by adimarco** [comment]
I'll set up a 1-line Lambda function behind API Gateway that does nothing but answer requests on one domain and issue 302 redirects to the other.  The ~$0.01/month it'll cost is a burden I'm willing to bear.  I just need to spend half an hour getting it set up.  I'll do that in the morning.

**Comment by matthewkmayer** [comment]
I'm going to try an S3-backed Cloudfront version of the gitbooks output.  We've been unable to have gitbook work as desired due to domain/DNS fun.  

Cloudfront should get us https, R53 will get us https://rusoto.org and https://www.rusoto.org, TravisCI can upload to an S3 bucket after builds.

**Comment by matthewkmayer** [comment]
The bucket is in place, I grabbed `master` and deployed it.  Cloudfront set up, redirects http to https.  Route53 set up so both http://rusoto.org and www.rusoto.org redirect to Cloudfront and switch over to https. 🎉 

Remaining: set up TravisCI to publish to the S3 bucket from this repo.

**Comment by matthewkmayer** [comment]
After a bunch of PRs struggling with why the deploy wouldn't work, it's working now.  Anything merged into `source` will get published to the S3 bucket, fronted by Cloudfront.  http://rusoto.org works, https://rusoto.org works, http://www.rusoto.org works, https://www.rusoto.org works.

We're done here!
