### ISSUE TITLE
Choose and register a domain name

### ISSUE THREAD

**Issue by indiv0** [rusoto/rusoto.github.io#9]
See prior discussion here: https://github.com/rusoto/rusoto/issues/366

Two obvious choices would be `rusoto.rs` and `rusoto.org`. This issue is low priority because we can safely continue using `https://rusoto.github.io` for now.

**Comment by matthewkmayer** [comment]
I've got the ball rolling for rusoto.org.

**Comment by indiv0** [comment]
Looks like with your changes to the settings and #12, everything works!

We have:
- `http://rusoto.org`
- `http://www.rusoto.org -> http://rusoto.org`
- `http://rusoto.github.io -> http://rusoto.org`

Sadly, it looks like we've lost SSL (unless we configure Cloudflare as a proxy to provide the SSL).
We'll get it back if GitHub Pages provides us an account and allows us to configure our custom domain with it.

**Comment by indiv0** [comment]
Closing and moving SSL to a separate issue.
