### ISSUE TITLE
Add information on using a proxy

### ISSUE THREAD

**Issue by matthewkmayer** [rusoto/rusoto.github.io#94]
https://github.com/rusoto/rusoto/issues/1172 is an example of wanting to use a proxy with a Rusoto crate. We should have good docs on how to do this.

**Comment by meghashyam6** [comment]
@matthewkmayer is it even possible with current version to set a proxy? or needs an enhancement/code change?

**Comment by matthewkmayer** [comment]
More details are in https://github.com/rusoto/rusoto/issues/1172 but I plan on having an example on https://rusoto.org . 👍

**Comment by matthewkmayer** [comment]
Two years and no progress - not gonna happen. 😿
